version: "3.9"

services:
  # Weight Service
  weightdb:
    build: ../Weight/db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  weight:
    build: ../Weight/app
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST_WEIGHT}
      DB_NAME: ${DB_NAME_WEIGHT}
    volumes:
      - ../Weight/in:/in
    depends_on:
      weightdb:
        condition: service_healthy
    ports:
      - "8081:5005"

  # Billing Service
  billingdb:
    build: ../Billing/db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  billing:
    build: ../Billing/app
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST_BILLING}
      DB_NAME: ${DB_NAME_BILLING}
    volumes:
      - ../Billing/in:/in
    depends_on:
      billingdb:
        condition: service_healthy
    ports:
      - "8082:5002"

  # CI Manager
  ci:
    build: .
    env_file: .env
    environment:
      WEIGHT_URL: ${WEIGHT_URL}
      BILLING_URL: ${BILLING_URL}
    depends_on:
      - weight
      - billing
    ports:
      - "8080:8080"

  # Integration Tests
  tester:
    build: .
    command: ["python", "-m", "pytest", "-q", "tests_int"]
    volumes:
      - ../Billing/tests:/tests_billing
      - ../Weight/tests:/tests_weight
      - ./tests_int:/tests_int
    depends_on:
      - weight
      - billing
    profiles:
      - testing