services:
  ci:
    container_name: my-ci
    build: .
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/logs:/logs
    environment:
      - SLACK_WEBHOOK_URL
    ports:
      - 8080:8080
    networks:
      - gan-shmuel

networks:
  gan-shmuel:
