version: '3.8'

services:
  ci-app:
    build: .
    container_name: ci_app
    expose:
      - "8080"
    networks:
      - ci-network

  nginx:
    image: nginx:alpine
    container_name: ci_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./key.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - ci-app
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge
