version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  flask-app:
    build:
      context: ./app
    container_name: flask-app
    depends_on:
      - db
    ports:
      - "8081:5000"
    env_file:
      - .env                      # ← read in FLASK_SECRET_KEY (and your DB_ vars if you like)
    environment:
      DB_HOST:      db
      DB_NAME:      ${MYSQL_DATABASE}
      DB_USER:      ${MYSQL_USER}
      DB_PASSWORD:  ${MYSQL_PASSWORD}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}  # ← now available inside the container
    volumes:
      - ./app/templates:/app/templates
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
