version: "3.9"

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5003
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development     
    volumes:
      - .:/app              
    ports:
      - "5003:5003"

  tests:
    build: .
    command: pytest -q
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app
