services:
  web_weight:
    container_name: weight-app
    build:
      context: .
    ports:
      - "8082:5000"
    depends_on:
      db_weight:
        condition: service_healthy
    environment:
      DB_HOST: db_weight
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./app:/app/app  # Optional: hot-reload if desired
    command: ["python", "-m", "app.main.py"]
    networks:
      - gan-shmuel

  db_weight:
    container_name: weight-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - gsdata:/var/lib/mysql
      - ./weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gan-shmuel

networks:
  gan-shmuel:
    external: true

volumes:
  gsdata: