services:
  db:
    image: mysql:8.0
    container_name: weight-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jerusalem
    volumes:
      - db_data:/var/lib/mysql
      - ./weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
    ports:
      - "3306:3306"
  app:
    build:
      context: ./app
    container_name: weight-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TZ: Asia/Jerusalem
    volumes:
      - ./app:/app/app  # Mount just your app code for hot-reload (optional)
      - ./tests:/app/tests
    command: ["python", "-m", "app.main"]
volumes:
  db_data: