services:
  db:
    image: mysql:8.0
    container_name: weight-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jerusalem
    volumes:
      - db_data:/var/lib/mysql
      - ./weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    command: --default-time-zone='+03:00'

  app:
    build:
      context: .
    container_name: weight-app
    ports:
      - "8082:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TZ: Asia/Jerusalem
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["python", "-m", "app.main"]

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: weight-frontend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - app
  #   environment:
  #     TZ: Asia/Jerusalem
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

volumes:
  db_data: {}
