# Weight/db/Dockerfile
FROM mysql:8.0

# Set default database configuration
ENV MYSQL_ROOT_PASSWORD=rootpassword \
    MYSQL_DATABASE=weightdb \
    MYSQL_USER=weightuser \
    MYSQL_PASSWORD=weightpassword

EXPOSE 3306
